#include "arduino_secrets.h"
#include <ArduinoHttpClient.h>
#include <SGP30.h>
#include <LCD_I2C.h>
#include "thingProperties.h"
#include "Adafruit_SGP30.h"
#include "DHT.h"
#define DHTPIN 2     // Digital pin connected to the DHT sensor
#define DHTTYPE DHT22   // DHT 22  (AM2302), AM2321



/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/1cab5706-130c-4e3d-9767-9458cee4d7a2 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  float temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/



uint16_t TVOC_base, eCO2_base, TVOC, eCO2;
int counter = 0;
const int buzzer = 8;
int alarmCounter = 0;
bool alert = false;
int alarmDelay = 60;     //Delay between how often you want text sent to phone. Measured in seconds roughly. Example if set to 30 seconds, the fastest a text will send if labnoses is alerted is 1 text every 30 seconds



LCD_I2C lcd(0x27, 16, 2);    //Default address of LCD Screen. Initializes lcd object
Adafruit_SGP30 sgp; //Initialize sgp (VOC Sensor) object
DHT dht(DHTPIN, DHTTYPE); //Initialize DHT Object

// IFTTT credentials
const char* ifttt_key = "https://maker.ifttt.com/trigger/DHT_Text_Service/with/key/bhElJ32v3Uwvue-UBStIhU";
const char* ifttt_event = "DHT_Text_Service";


// Server details
const char* server = "maker.ifttt.com";
const int port = 443;

WiFiSSLClient wifiClient;
HttpClient client = HttpClient(wifiClient, server, port);


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  //This begins the LabNose SetUP process
  Serial.begin(9600);
  lcd.begin();
  lcd.backlight();
  sgp.begin();
  dht.begin();
  pinMode(buzzer,OUTPUT); //Initializes buzzer pin 8
  
}

void loop() {
  ArduinoCloud.update();

  

  TVOC = sgp.TVOC;  //Total TVOC detected by SGP30 Sensor measured in ppb
  cloudVOC = int(TVOC);
  eCO2 = sgp.eCO2;  //Total eCO2 detected by SGP30 sesnor measured in ppm
  cloudCO2 = eCO2;
 
  
  float h = dht.readHumidity();
  cloudHumidity = h;
  float t = dht.readTemperature();
  cloudTemperature = t;
  float f = dht.readTemperature(true);

  

  // Check if any reads failed and exit early (to try again).
  if (isnan(h) || isnan(t) || isnan(f)) {
    Serial.println(F("Failed to read from DHT sensor!"));
    return;
  }



  if (! sgp.IAQmeasure()) {
    Serial.println("Measurement failed");
    return;
  }

  //Print info into LCD Screen
  lcd.print("TVOC:  "); lcd.print (TVOC); lcd.print(" ppb");
  lcd.setCursor(0,1);
  lcd.print("eCO2:  "); lcd.print(eCO2); lcd.print( "ppm");
  delay(1000);
  lcd.clear();

  //Print info into Serial Monitor for testing
  Serial.print("TVOC "); Serial.print(sgp.TVOC); Serial.print(" ppb\t");
  Serial.print("eCO2 "); Serial.print(sgp.eCO2); Serial.println("  ppm");

  
  Serial.print(F("Humidity: "));
  Serial.print(h);
  Serial.print(F("%  Temperature: "));
  Serial.print(t);
  Serial.println();

  if(TVOC >= 1000){
    if(alert == false){
      sendIFTTTEvent(cloudVOC,cloudTemperature,cloudHumidity);
    }
    
    tone(buzzer,1000);
    alarmCounter++;
    alert = true;
    
  }
  else{
    noTone(buzzer);
    alarmCounter++;
  }

  if (alarmCounter == alarmDelay){
    alert = false;
    alarmCounter = 0;
  }

 
  counter++;
  if (counter == 30) {
    counter = 0;

    uint16_t TVOC_base, eCO2_base;
    if (! sgp.getIAQBaseline(&eCO2_base, &TVOC_base)) {
      Serial.println("Failed to get baseline readings");
      return;
    }
    Serial.print("****Baseline values: eCO2: 0x"); Serial.print(eCO2_base, HEX);
    Serial.print(" & TVOC: 0x"); Serial.println(TVOC_base, HEX);
  }

 

  
}



void sendIFTTTEvent(int VOC,int temp, int humidity ) {
  String valueURL = "?value1="+String(VOC)+"&value2="+String(temp)+"&value3="+String(humidity);
  String url = "/trigger/LabNose/with/key/fybYYR_bYWdXEdU1xRkxrmct1gmmnIULWEdZQv65Vk5" + valueURL;

  client.get(url);
  int statusCode = client.responseStatusCode();
  String response = client.responseBody();

  Serial.println("Status code: " + String(statusCode));
  Serial.println("Response: " + response);
}




/*
  Since CloudCO2 is READ_WRITE variable, onCloudCO2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudCO2Change()  {
  // Add your code here to act upon CloudCO2 change
}
/*
  Since CloudHumidity is READ_WRITE variable, onCloudHumidityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudHumidityChange()  {
  // Add your code here to act upon CloudHumidity change
}
/*
  Since CloudTemperature is READ_WRITE variable, onCloudTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudTemperatureChange()  {
  // Add your code here to act upon CloudTemperature change
}
/*
  Since CloudVOC is READ_WRITE variable, onCloudVOCChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCloudVOCChange()  {
  // Add your code here to act upon CloudVOC change
}
/*
  Since Alarm is READ_WRITE variable, onAlarmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAlarmChange()  {
  // Add your code here to act upon Alarm change
}










